### ISSUE TITLE
Project status?

### ISSUE THREAD

**Issue by george-wilson-rea** [etorreborre/specs2-cats#134]
What's the status of specs2-cats?

I notice that there's no 5.x release of specs2-cats like there is with specs2-core and specs2-scalacheck.
Is this project abandoned, or maybe do you need some help finishing something off before you can release it? I liked when all the specs2 sub components had the same version - could we version this one as 5.2.0 or 5.3.0 so that it matches specs2-core etc.?

**Comment by armanbilge** [comment]
> What's the status of specs2-cats?

It has working integrations with Cats Effect, Scalacheck Effect, etc. Have you tried it, did you have some problems? :)

> or maybe do you need some help finishing something off before you can release it?

There are published releases available, and I'd appreciate help on any open issues.

> could we version this one as 5.2.0 or 5.3.0 so that it matches specs2-core etc.

I'm not really sure if it makes sense. Since it is published from a separate repository, the versioning is not required to match up. Indeed, suppose we want to release a bug fix here, how can we do that without waiting for another release of specs2-core, or putting the versions out of sync again?

**Comment by george-wilson-rea** [comment]
Ah ok, I was looking at maven and 4.19.2 looked like the last release of specs2-cats. Looks like you've reset the versioning to 1.0? That's unexpected because it's less than 4. I would have expected the version number to go forward (if you wanted the version to be distinct from specs2 itself, perhaps you could set the version to 10.0 or something like that, after 5.0)

Beyond the numbering situation, It also looks like 1.0 has been in "alpha" for a long time. I can use the alphas, but are there plans for a release?

**Comment by armanbilge** [comment]
> Looks like you've reset the versioning to 1.0?

Hum, history of this project starts from 1.0.0-ALPHA-00, which I continued when I started maintaining as of ALPHA-02.

https://github.com/etorreborre/specs2-cats/tags

> Beyond the numbering situation, It also looks like 1.0 has been in "alpha" for a long time. I can use the alphas, but are there plans for a release?

You are right, it's been stable for a while, but I haven't been sure if that's because it's working well, or because Scala 3 adoption is small and there has not been enough use yet :) if we are confident to lock down compatibility with current APIs, then we can cut a stable release.

**Comment by george-wilson-rea** [comment]
What about all the releases listed here? https://mvnrepository.com/artifact/org.specs2/specs2-cats
eg. 4.19.2

**Comment by armanbilge** [comment]
Thanks, I wasn't aware of that. It looks like we have an artifact name clash, so we should publish this project under a new name.

Edit: or, as you say, advance the versioning to 5.x.x. hmmm 🤔

**Comment by george-wilson-rea** [comment]
>artifact name clash

Ah, that makes sense. I see what's happening now. The main specs2 repo is still publishing releases under this name in its 4.x branch, while you're working here.

Thanks for the help! Good luck with the naming or versioning situation. I like the 5.x.x version idea better than the renaming idea, but I'm only one user :)
